import { useEffect, useState } from "react";
import { useLocation } from "react-router-dom";
import { Droplets, Factory, Fan, Recycle, ShieldCheck, Wrench } from "lucide-react";
import StickyHeader from "@/components/StickyHeader";
import Footer from "@/components/Footer";

type ClientLogo = {
  name: string;
  logoUrl?: string;
};

type Division = {
  id: string;
  title: string;
  shortTitle: string;
  icon: typeof Factory;
  accent: string;
  summary: string;
  bullets: string[];
  clients: ClientLogo[];
};

const logoUrl = (domain: string) => `https://logo.clearbit.com/${domain}`;

const divisions: Division[] = [
  {
    id: "industrial-cooling-boiler-ro-water-treatment-division",
    title: "Industrial Cooling, Boiler and RO Water Treatment Division",
    shortTitle: "Cooling, Boiler and RO",
    icon: Factory,
    accent: "from-ionic-blue to-ionic-orange",
    summary:
      "Focuses on the purification, treatment, and management of water used in cooling, boiler, and reverse osmosis systems using high-quality chemicals and equipment.",
    bullets: [
      "Provides equipment, materials, and chemicals for cooling systems, boilers, and reverse osmosis applications.",
      "Supports operating efficiency, water quality, and plant reliability through targeted treatment programs.",
    ],
    clients: [
      { name: "Excellent Energy Resources, Inc. (EERI)", logoUrl: logoUrl("eeri.com.ph") },
      { name: "Linseed Field Corporation", logoUrl: logoUrl("linseed.com.ph") },
      { name: "PNOC", logoUrl: logoUrl("pnoc.com.ph") },
      { name: "San Miguel Global Power", logoUrl: logoUrl("smgp.com.ph") },
      { name: "DMCI Power Corporation", logoUrl: logoUrl("dmcipower.com") },
      { name: "Semirara Mining & Power Corporation", logoUrl: logoUrl("semirara.com") },
      { name: "CSI Malls", logoUrl: logoUrl("csimalls.com") },
    ],
  },
  {
    id: "airconditioning-division",
    title: "Airconditioning Division",
    shortTitle: "Airconditioning",
    icon: Fan,
    accent: "from-ionic-orange to-ionic-blue",
    summary:
      "Specializes in comprehensive solutions for cooling systems and air conditioning in various industrial and commercial settings.",
    bullets: [
      "Covers water treatment for cooling systems, installation of new cooling units, servicing, cleaning, and parts replacement.",
      "Keeps critical environments stable with practical maintenance and dependable technical support.",
    ],
    clients: [
      { name: "Office of the President of the Philippines", logoUrl: logoUrl("presidency.gov.ph") },
      { name: "National Museum Pambansang Museo", logoUrl: logoUrl("nationalmuseum.gov.ph") },
      { name: "Bangko Sentral ng Pilipinas", logoUrl: logoUrl("bsp.gov.ph") },
    ],
  },
  {
    id: "preventive-maintenance-chemicals-division",
    title: "Preventive Maintenance Chemicals Division",
    shortTitle: "Preventive Chemicals",
    icon: Wrench,
    accent: "from-ionic-blue to-sky-600",
    summary:
      "Specializes in providing a comprehensive range of chemical solutions and services aimed at preventive maintenance and optimization of industrial equipment and processes.",
    bullets: [
      "Supplies chemicals and services for pipe cleaning, passivation, pre-operational cleaning, start-up, and commissioning.",
      "Supports a spectrum of industries that need consistent equipment performance and cleaner operational systems.",
    ],
    clients: [
      { name: "Excellent Energy Resources, Inc. (EERI)", logoUrl: logoUrl("eeri.com.ph") },
      { name: "Linseed Field Corporation", logoUrl: logoUrl("linseed.com.ph") },
      { name: "Carmelray Industrial Corporation", logoUrl: logoUrl("carmelray.com") },
      { name: "Southwest Luzon Power Generation Corporation", logoUrl: logoUrl("slpgc.com") },
      { name: "Continental", logoUrl: logoUrl("continental.com") },
      { name: "AG&P", logoUrl: logoUrl("agp.com.ph") },
    ],
  },
  {
    id: "wastewater-treatment-division",
    title: "Wastewater Treatment Division",
    shortTitle: "Wastewater",
    icon: Recycle,
    accent: "from-emerald-600 to-ionic-blue",
    summary:
      "Dedicated to providing comprehensive and customized solutions for the purification, treatment, and management of wastewater generated by industrial and municipal sources.",
    bullets: [
      "Uses biological, physico-chemical, filtration, disinfection, and sludge management technologies to meet compliance needs.",
      "Helps clients achieve regulatory discharge, effluent quality, and environmental protection requirements.",
    ],
    clients: [
      { name: "Cultural Center of the Philippines", logoUrl: logoUrl("culturalcenter.gov.ph") },
      { name: "DMCI Power Corporation", logoUrl: logoUrl("dmcipower.com") },
      { name: "CSI Dagupan Mall", logoUrl: logoUrl("csimalls.com") },
      { name: "Magic Mall Urdaneta", logoUrl: logoUrl("magicmallurdaneta.com") },
    ],
  },
  {
    id: "oil-grease-and-lubricant-division",
    title: "Oil, Grease, and Lubricant Division",
    shortTitle: "Oil, Grease and Lubricant",
    icon: Droplets,
    accent: "from-amber-500 to-ionic-orange",
    summary:
      "Specializes in providing a comprehensive range of high-quality oils, greases, and lubricants tailored to the needs of various industries and applications.",
    bullets: [
      "Recommends suitable products for different equipment types, operating conditions, and performance requirements.",
      "Focuses on extended equipment life, reduced wear, improved efficiency, corrosion protection, and operational reliability.",
    ],
    clients: [
      { name: "Carmelray Industrial Corporation", logoUrl: logoUrl("carmelray.com") },
      { name: "Continental", logoUrl: logoUrl("continental.com") },
      { name: "ATEC Automated Technology (Phil.) Inc.", logoUrl: logoUrl("atec.com.ph") },
    ],
  },
  {
    id: "oil-spill-supplies-division",
    title: "Oil Spill Supplies Division",
    shortTitle: "Oil Spill Supplies",
    icon: ShieldCheck,
    accent: "from-slate-700 to-ionic-blue",
    summary:
      "Dedicated to providing high-quality chemicals, materials, and equipment such as sorbent materials and dispersants for oil spills, helping protect ecosystems and communities.",
    bullets: [
      "Supports oil-spill response with sorbent materials and dispersant products for fast containment and removal.",
      "Includes a specialized marine oil dispersant, MAGIC CHEM (OSD) 1280, for water-surface cleanup and affected areas.",
    ],
    clients: [
      { name: "San Nicholas Lines, Inc.", logoUrl: logoUrl("sannicholaslines.com") },
      { name: "Pherwin Shipping Corp.", logoUrl: logoUrl("pherwinshipping.com") },
      { name: "Philippine Coast Guard", logoUrl: logoUrl("coastguard.gov.ph") },
    ],
  },
];

const romanNumerals = ["I", "II", "III", "IV", "V", "VI"];

const clientInitials = (name: string) =>
  name
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((word) => word[0])
    .join("")
    .toUpperCase();

const ClientCard = ({
  client,
  dark = false,
}: {
  client: ClientLogo;
  dark?: boolean;
}) => {
  const [imageFailed, setImageFailed] = useState(false);

  return (
    <div
      className={`rounded-lg border p-3 flex flex-col items-center justify-center gap-2 h-28 text-center transition-transform hover:-translate-y-0.5 hover:shadow-md
        ${dark
          ? "border-white/10 bg-white/5"
          : "border-border bg-card"
        }`}
    >
      <div className="flex items-center justify-center h-10 w-10 rounded-full overflow-hidden bg-muted/10">
        {client.logoUrl && !imageFailed ? (
          <img
            src={client.logoUrl}
            alt={`${client.name} logo`}
            className="h-full w-full object-contain"
            loading="lazy"
            referrerPolicy="no-referrer"
            onError={() => setImageFailed(true)}
          />
        ) : (
          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-ionic-blue to-ionic-orange text-sm font-bold text-white">
            {clientInitials(client.name)}
          </div>
        )}
      </div>
      <p
        className={`text-xs leading-tight line-clamp-2 ${
          dark ? "text-primary-foreground/80" : "text-foreground"
        }`}
      >
        {client.name}
      </p>
    </div>
  );
};

const Divisions = () => {
  const { hash } = useLocation();

  useEffect(() => {
    if (!hash) return;
    const target = document.getElementById(decodeURIComponent(hash.slice(1)));
    if (!target) return;
    const frame = window.requestAnimationFrame(() => {
      target.scrollIntoView({ behavior: "smooth", block: "start" });
    });
    return () => window.cancelAnimationFrame(frame);
  }, [hash]);

  return (
    <>
    <StickyHeader />
      {/* ── 1. OVERVIEW — dark bg ── */}
      <section
        id="divisions-overview"
        className="section-padding min-h-screen gradient-hero flex items-center scroll-mt-24"
      >
        <div className="container-narrow w-full grid gap-10 lg:grid-cols-[1.1fr_0.9fr] items-center">
          <div className="space-y-5">
            <p className="text-xs font-semibold uppercase tracking-[0.3em] text-primary-foreground/60">
              Our Divisions
            </p>
            <h1 className="text-3xl md:text-4xl lg:text-5xl font-extrabold leading-tight text-primary-foreground">
              Overview of <span className="text-gradient-orange">Divisions</span>
            </h1>
            <p className="text-base md:text-lg leading-relaxed text-primary-foreground/75 max-w-2xl">
              Six focused divisions support industrial, commercial, and
              public-sector clients across water treatment, maintenance
              chemicals, wastewater systems, lubricants, and spill response.
            </p>
          </div>

          {/* Jump nav */}
          <nav className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary-foreground/60 mb-4">
              Jump to a division
            </p>
            <ul className="space-y-1">
              {divisions.map((division, index) => (
                <li key={division.id}>
                  <a
                    href={`#${division.id}`}
                    className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-primary-foreground/90 hover:bg-white/10 transition-colors"
                  >
                    <span className="shrink-0 w-6 text-xs font-bold text-ionic-orange">
                      {romanNumerals[index]}
                    </span>
                    <span className="truncate">{division.shortTitle}</span>
                  </a>
                </li>
              ))}
            </ul>
          </nav>
        </div>
      </section>

      {/* ── 2–7. DIVISION SECTIONS — alternating light / dark ── */}
      {divisions.map((division, index) => {
        const isDark = index % 2 !== 0; // even = light, odd = dark

        return (
          <section
            key={division.id}
            id={division.id}
            className={`section-padding min-h-screen flex items-center scroll-mt-24 ${
              isDark ? "gradient-hero" : "bg-background"
            }`}
          >
            <div className="container-narrow w-full">
              {/* Division header */}
              <div className="flex items-start gap-4 mb-6">
                <div
                  className={`flex h-14 w-14 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br ${division.accent} text-white shadow-elevated`}
                >
                  <division.icon size={24} />
                </div>
                <div>
                  <p
                    className={`text-xs font-semibold uppercase tracking-[0.25em] mb-1 ${
                      isDark
                        ? "text-primary-foreground/60"
                        : "text-muted-foreground"
                    }`}
                  >
                    Division {romanNumerals[index]}
                  </p>
                  <h2
                    className={`text-2xl md:text-3xl font-bold leading-snug ${
                      isDark ? "text-primary-foreground" : "text-foreground"
                    }`}
                  >
                    {division.title}
                  </h2>
                </div>
              </div>

              {/* Summary + bullets */}
              <p
                className={`text-base md:text-lg leading-relaxed mb-6 max-w-3xl ${
                  isDark ? "text-primary-foreground/75" : "text-muted-foreground"
                }`}
              >
                {division.summary}
              </p>

              <ul className="space-y-3 mb-10">
                {division.bullets.map((bullet) => (
                  <li key={bullet} className="flex items-start gap-3">
                    <span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-ionic-orange" />
                    <p
                      className={`text-sm md:text-base ${
                        isDark
                          ? "text-primary-foreground/85"
                          : "text-foreground/90"
                      }`}
                    >
                      {bullet}
                    </p>
                  </li>
                ))}
              </ul>

              {/* Clients */}
              <div>
                <p
                  className={`text-sm font-semibold uppercase tracking-widest mb-4 ${
                    isDark
                      ? "text-primary-foreground/60"
                      : "text-muted-foreground"
                  }`}
                >
                  Clients
                </p>
                <div className="grid gap-4 grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
                  {division.clients.map((client) => (
                    <ClientCard
                      key={client.name}
                      client={client}
                      dark={isDark}
                    />
                  ))}
                </div>
              </div>
            </div>
          </section>
        );
      })}
      <Footer />
    </>
  );
};

export default Divisions;