import { useEffect, useState } from "react";
import { useLocation } from "react-router-dom";
import { Droplets, Factory, Fan, Recycle, ShieldCheck, Wrench } from "lucide-react";

import StickyHeader from "@/components/StickyHeader";
import Footer from "@/components/Footer";
import heroBg4 from "@/assets/hero-bg-4.jpg";

type ClientLogo = {
  name: string;
  logoUrl?: string;
};

type Division = {
  id: string;
  title: string;
  shortTitle: string;
  icon: typeof Factory;
  accent: string;
  summary: string;
  bullets: string[];
  clients: ClientLogo[];
};

const logoUrl = (domain: string) => `https://logo.clearbit.com/${domain}`;

const divisions: Division[] = [
  {
    id: "industrial-cooling-boiler-ro-water-treatment-division",
    title: "Industrial Cooling, Boiler and RO Water Treatment Division",
    shortTitle: "Cooling, Boiler and RO",
    icon: Factory,
    accent: "from-ionic-blue to-ionic-orange",
    summary:
      "Focuses on the purification, treatment, and management of water used in cooling, boiler, and reverse osmosis systems using high-quality chemicals and equipment.",
    bullets: [
      "Provides equipment, materials, and chemicals for cooling systems, boilers, and reverse osmosis applications.",
      "Supports operating efficiency, water quality, and plant reliability through targeted treatment programs.",
    ],
    clients: [
      { name: "Excellent Energy Resources, Inc. (EERI)", logoUrl: logoUrl("eeri.com.ph") },
      { name: "Linseed Field Corporation", logoUrl: logoUrl("linseed.com.ph") },
      { name: "PNOC", logoUrl: logoUrl("pnoc.com.ph") },
      { name: "San Miguel Global Power", logoUrl: logoUrl("smgp.com.ph") },
      { name: "DMCI Power Corporation", logoUrl: logoUrl("dmcipower.com") },
      { name: "Semirara Mining & Power Corporation", logoUrl: logoUrl("semirara.com") },
      { name: "CSI Malls", logoUrl: logoUrl("csimalls.com") },
    ],
  },
  {
    id: "airconditioning-division",
    title: "Airconditioning Division",
    shortTitle: "Airconditioning",
    icon: Fan,
    accent: "from-ionic-orange to-ionic-blue",
    summary:
      "Specializes in comprehensive solutions for cooling systems and air conditioning in various industrial and commercial settings.",
    bullets: [
      "Covers water treatment for cooling systems, installation of new cooling units, servicing, cleaning, and parts replacement.",
      "Keeps critical environments stable with practical maintenance and dependable technical support.",
    ],
    clients: [
      { name: "Office of the President of the Philippines", logoUrl: logoUrl("presidency.gov.ph") },
      { name: "National Museum Pambansang Museo", logoUrl: logoUrl("nationalmuseum.gov.ph") },
      { name: "Bangko Sentral ng Pilipinas", logoUrl: logoUrl("bsp.gov.ph") },
    ],
  },
  {
    id: "preventive-maintenance-chemicals-division",
    title: "Preventive Maintenance Chemicals Division",
    shortTitle: "Preventive Chemicals",
    icon: Wrench,
    accent: "from-ionic-blue to-sky-600",
    summary:
      "Specializes in providing a comprehensive range of chemical solutions and services aimed at preventive maintenance and optimization of industrial equipment and processes.",
    bullets: [
      "Supplies chemicals and services for pipe cleaning, passivation, pre-operational cleaning, start-up, and commissioning.",
      "Supports a spectrum of industries that need consistent equipment performance and cleaner operational systems.",
    ],
    clients: [
      { name: "Excellent Energy Resources, Inc. (EERI)", logoUrl: logoUrl("eeri.com.ph") },
      { name: "Linseed Field Corporation", logoUrl: logoUrl("linseed.com.ph") },
      { name: "Carmelray Industrial Corporation", logoUrl: logoUrl("carmelray.com") },
      { name: "Southwest Luzon Power Generation Corporation", logoUrl: logoUrl("slpgc.com") },
      { name: "Continental", logoUrl: logoUrl("continental.com") },
      { name: "AG&P", logoUrl: logoUrl("agp.com.ph") },
    ],
  },
  {
    id: "wastewater-treatment-division",
    title: "Wastewater Treatment Division",
    shortTitle: "Wastewater",
    icon: Recycle,
    accent: "from-emerald-600 to-ionic-blue",
    summary:
      "Dedicated to providing comprehensive and customized solutions for the purification, treatment, and management of wastewater generated by industrial and municipal sources.",
    bullets: [
      "Uses biological, physico-chemical, filtration, disinfection, and sludge management technologies to meet compliance needs.",
      "Helps clients achieve regulatory discharge, effluent quality, and environmental protection requirements.",
    ],
    clients: [
      { name: "Cultural Center of the Philippines", logoUrl: logoUrl("culturalcenter.gov.ph") },
      { name: "DMCI Power Corporation", logoUrl: logoUrl("dmcipower.com") },
      { name: "CSI Dagupan Mall", logoUrl: logoUrl("csimalls.com") },
      { name: "Magic Mall Urdaneta", logoUrl: logoUrl("magicmallurdaneta.com") },
    ],
  },
  {
    id: "oil-grease-and-lubricant-division",
    title: "Oil, Grease, and Lubricant Division",
    shortTitle: "Oil, Grease and Lubricant",
    icon: Droplets,
    accent: "from-amber-500 to-ionic-orange",
    summary:
      "Specializes in providing a comprehensive range of high-quality oils, greases, and lubricants tailored to the needs of various industries and applications.",
    bullets: [
      "Recommends suitable products for different equipment types, operating conditions, and performance requirements.",
      "Focuses on extended equipment life, reduced wear, improved efficiency, corrosion protection, and operational reliability.",
    ],
    clients: [
      { name: "Carmelray Industrial Corporation", logoUrl: logoUrl("carmelray.com") },
      { name: "Continental", logoUrl: logoUrl("continental.com") },
      { name: "ATEC Automated Technology (Phil.) Inc.", logoUrl: logoUrl("atec.com.ph") },
    ],
  },
  {
    id: "oil-spill-supplies-division",
    title: "Oil Spill Supplies Division",
    shortTitle: "Oil Spill Supplies",
    icon: ShieldCheck,
    accent: "from-slate-700 to-ionic-blue",
    summary:
      "Dedicated to providing high-quality chemicals, materials, and equipment such as sorbent materials and dispersants for oil spills, helping protect ecosystems and communities.",
    bullets: [
      "Supports oil-spill response with sorbent materials and dispersant products for fast containment and removal.",
      "Includes a specialized marine oil dispersant, MAGIC CHEM (OSD) 1280, for water-surface cleanup and affected areas.",
    ],
    clients: [
      { name: "San Nicholas Lines, Inc.", logoUrl: logoUrl("sannicholaslines.com") },
      { name: "Pherwin Shipping Corp.", logoUrl: logoUrl("pherwinshipping.com") },
      { name: "Philippine Coast Guard", logoUrl: logoUrl("coastguard.gov.ph") },
    ],
  },
];

const romanNumerals = ["I", "II", "III", "IV", "V", "VI"];

const clientInitials = (name: string) =>
  name
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((word) => word[0])
    .join("")
    .toUpperCase();

const ClientCard = ({ client }: { client: ClientLogo }) => {
  const [imageFailed, setImageFailed] = useState(false);

  return (
    <div className="rounded-lg border border-border bg-card p-3 flex flex-col items-center justify-center gap-2 h-28 text-center transition-transform hover:-translate-y-0.5 hover:shadow-md">
      <div className="flex items-center justify-center h-10 w-10 rounded-full bg-muted/10 overflow-hidden">
        {client.logoUrl && !imageFailed ? (
          <img
            src={client.logoUrl}
            alt={`${client.name} logo`}
            className="h-full w-full object-contain"
            loading="lazy"
            referrerPolicy="no-referrer"
            onError={() => setImageFailed(true)}
          />
        ) : (
          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-ionic-blue to-ionic-orange text-sm font-bold text-white">
            {clientInitials(client.name)}
          </div>
        )}
      </div>
      <p className="text-xs leading-tight text-foreground line-clamp-2">{client.name}</p>
    </div>
  );
};

const Divisions = () => {
  const { hash } = useLocation();

  useEffect(() => {
    if (!hash) {
      return;
    }

    const target = document.getElementById(decodeURIComponent(hash.slice(1)));
    if (!target) {
      return;
    }

    const frame = window.requestAnimationFrame(() => {
      target.scrollIntoView({ behavior: "smooth", block: "start" });
    });

    return () => window.cancelAnimationFrame(frame);
  }, [hash]);

  return (
    <>
      <StickyHeader />
      <main className="w-full py-12 md:py-16 lg:py-20">
        <section id="divisions-overview" className="bg-slate-900 text-primary-foreground py-12 md:py-16 scroll-mt-24">
          <div className="max-w-7xl mx-auto px-4 md:px-8">
            <div className="grid gap-8 lg:grid-cols-[1.1fr_0.9fr] items-center">
              <div className="space-y-5">
                <p className="text-xs font-semibold uppercase tracking-[0.3em] text-primary-foreground/70">Our Divisions</p>
                <h1 className="text-3xl md:text-4xl lg:text-5xl font-extrabold leading-tight">Overview of Divisions</h1>
                <p className="text-base md:text-lg leading-relaxed text-primary-foreground/80 max-w-3xl">
                  Six focused divisions support industrial, commercial, and public-sector clients across water treatment, maintenance chemicals, wastewater systems, lubricants, and spill response.
                </p>
              </div>

              <nav className="rounded-lg border border-white/5 bg-white/5 p-4">
                <p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary-foreground/70 mb-3">Jump to a division</p>
                <ul className="space-y-2">
                  {divisions.map((division, index) => (
                    <li key={division.id}>
                      <a
                        href={`#${division.id}`}
                        className="flex items-center justify-between gap-4 rounded-md px-3 py-2 text-sm font-medium text-primary-foreground/95 hover:bg-white/10"
                      >
                        <span className="truncate">{romanNumerals[index]}. {division.shortTitle}</span>
                      </a>
                    </li>
                  ))}
                </ul>
              </nav>
            </div>
          </div>
        </section>

        {divisions.map((division, index) => (
          <section
            key={division.id}
            id={division.id}
            className="scroll-mt-24 border-t border-border bg-background py-12"
          >
            <div className="max-w-7xl mx-auto px-4 md:px-8">
              <div className="grid gap-8 lg:grid-cols-[1fr_320px] items-start">
                <div>
                  <div className="flex items-start gap-4 mb-4">
                    <div className={`flex h-14 w-14 shrink-0 items-center justify-center rounded-lg ${division.accent} text-white`}>
                      <division.icon size={22} />
                    </div>
                    <div>
                      <p className="text-xs font-semibold uppercase tracking-[0.25em] text-muted-foreground mb-1">Division {romanNumerals[index]}</p>
                      <h2 className="text-xl md:text-2xl font-bold text-foreground">{division.title}</h2>
                    </div>
                  </div>

                  <p className="text-base md:text-lg leading-relaxed text-muted-foreground mb-6">{division.summary}</p>

                  <ul className="space-y-3 mb-6">
                    {division.bullets.map((bullet) => (
                      <li key={bullet} className="flex items-start gap-3">
                        <span className="mt-1 h-2.5 w-2.5 rounded-full bg-ionic-orange" />
                        <p className="text-sm md:text-base text-foreground/90">{bullet}</p>
                      </li>
                    ))}
                  </ul>

                  <div className="mt-6">
                    <p className="text-sm font-semibold mb-3">Clients</p>
                    <div className="grid gap-4 grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-3 xl:grid-cols-4">
                      {division.clients.map((client) => (
                        <ClientCard key={client.name} client={client} />
                      ))}
                    </div>
                  </div>
                </div>

                <div className="pl-2">
                  <div className="rounded-lg border border-border bg-card p-4">
                    <p className="text-sm font-semibold uppercase tracking-[0.18em] text-muted-foreground mb-3">About this division</p>
                    <p className="text-sm leading-relaxed text-muted-foreground">More details, case studies, or sector notes can go here. This side panel keeps supporting information tidy and easily scannable.</p>
                  </div>
                </div>
              </div>
            </div>
          </section>
        ))}
      </main>
      <Footer />
    </>
  );
};

export default Divisions;
